---
- 
  name: insider_threat
  description: "it's coming from inside the house!"
  extra_info: "local origin sensor running suspicious executable"
  query: ClientAddr='127.0.0.1'
  actions: 
    - alert
  indicator_type: custom
  score: 60
